const examples = [
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
    {
        methodA: "Text generated by method A...",
        methodB: "Text generated by method B...",
        methodC: "Text generated by method C...",
    },
];
