const examples = [
    {
        methodA: "Text generated by method A1...",
        methodB: "Text generated by method B1...",
        methodC: "Text generated by method C1...",
    },
    {
        methodA: "Text generated by method A2...",
        methodB: "Text generated by method B2...",
        methodC: "Text generated by method C2...",
    },
    {
        methodA: "Text generated by method A3...",
        methodB: "Text generated by method B3...",
        methodC: "Text generated by method C3...",
    },
    {
        methodA: "Text generated by method A4...",
        methodB: "Text generated by method B4...",
        methodC: "Text generated by method C4...",
    },
    {
        methodA: "Text generated by method A5...",
        methodB: "Text generated by method B5...",
        methodC: "Text generated by method C5...",
    },
    {
        methodA: "Text generated by method A6...",
        methodB: "Text generated by method B6...",
        methodC: "Text generated by method C6...",
    },
    {
        methodA: "Text generated by method A1...",
        methodB: "Text generated by method B1...",
        methodC: "Text generated by method C1...",
    },
    {
        methodA: "Text generated by method A2...",
        methodB: "Text generated by method B2...",
        methodC: "Text generated by method C2...",
    },
    {
        methodA: "Text generated by method A3...",
        methodB: "Text generated by method B3...",
        methodC: "Text generated by method C3...",
    },
    {
        methodA: "Text generated by method A4...",
        methodB: "Text generated by method B4...",
        methodC: "Text generated by method C4...",
    },
    {
        methodA: "Text generated by method A5...",
        methodB: "Text generated by method B5...",
        methodC: "Text generated by method C5...",
    },
    {
        methodA: "Text generated by method A6...",
        methodB: "Text generated by method B6...",
        methodC: "Text generated by method C6...",
    },
    {
        methodA: "Text generated by method A1...",
        methodB: "Text generated by method B1...",
        methodC: "Text generated by method C1...",
    },
    {
        methodA: "Text generated by method A2...",
        methodB: "Text generated by method B2...",
        methodC: "Text generated by method C2...",
    },
    {
        methodA: "Text generated by method A3...",
        methodB: "Text generated by method B3...",
        methodC: "Text generated by method C3...",
    },
    {
        methodA: "Text generated by method A4...",
        methodB: "Text generated by method B4...",
        methodC: "Text generated by method C4...",
    },
    {
        methodA: "Text generated by method A5...",
        methodB: "Text generated by method B5...",
        methodC: "Text generated by method C5...",
    },
    {
        methodA: "Text generated by method A6...",
        methodB: "Text generated by method B6...",
        methodC: "Text generated by method C6...",
    },
];
